apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registrocivil-pdisciplinario-__CI_ENVIRONMENT_SLUG__
  labels:
    app: registrocivil-pdisciplinario
    ref: __CI_ENVIRONMENT_SLUG__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
